[build]
  builder = "nixpacks"
  buildCommand = "bash build.sh"
  nixpacks = { version = "1.0.0" }

[deploy]
  startCommand = "yarn start"

[build.environment]
  NVM_DIR = "/root/.nvm"
  NODE_VERSION = "18.0.0"
  NPM_CONFIG_PRODUCTION = "false"
  YARN_VERSION = "1.22.22"
  PATH = "/root/.nvm/versions/node/v18.0.0/bin:$PATH"
